# ----------------------------------------
# SDK配置文件   证书的存放路径根据实际情况配置，交易地址和证书根据PM环境、生产环境配套配置
# ----------------------------------------
# Development environment
spring:
  # PROFILES
  profiles: development
#交易请求地址  
acpsdk:
  #商户ID
  merId: 777290058127880
  
  ##交易请求地址 
  
  frontRequestUrl: https://101.231.204.80:5000/gateway/api/frontTransReq.do
  backRequestUrl: https://101.231.204.80:5000/gateway/api/backTransReq.do
  singleQueryUrl: https://101.231.204.80:5000/gateway/api/queryTrans.do
  batchTransUrl: https://101.231.204.80:5000/gateway/api/batchTrans.do
  fileTransUrl: https://101.231.204.80:9080/
  appRequestUrl: https://101.231.204.80:5000/gateway/api/appTransReq.do
  cardRequestUrl: https://101.231.204.80:5000/gateway/api/cardTransReq.do
  
   #linux下（注意：在linux下读取证书需要保证证书有被应用读的权限）
  sign-Cert-Path: /assets/acp_test_sign.pfx
    ##签名证书密码，测试环境固定000000，生产环境请修改为从cfca下载的正式证书的密码，正式环境证书密码位数需小于等于6位，否则上传到商户服务网站会失败
  sign-Cert-Pwd: '000000'
    ##签名证书类型，固定不需要修改
  sign-Cert-Type: PKCS12
  ##########################验签证书配置################################
  ##验证签名证书目录，只配置到目录即可，必须使用绝对路径，如果不想使用绝对路径，可以自行实现相对路径获取证书的方法；测试证书所有商户共用开发包中的测试验证证书，生产环境所有商户共用开发包中的生产验签证书
  #windows下
  #acpsdk.validateCert.dir=D:/certs/
  #linux下（注意：在linux下读取证书需要保证证书有被应用读的权限）
  validate-Cert-Dir: /assets/
   
    
  ##########################加密证书配置################################
  ##敏感信息加密证书路径(商户号开通了商户对敏感信息加密的权限，需要对 卡号accNo，pin和phoneNo，cvn2，expired加密（如果这些上送的话），对敏感信息加密使用)
  encrypt-Cert-Path: /assets/acp_test_enc.cer
  singleMode: true
  
  encrypt-Track-Cert-Path: ''
  encrypt-Track-Key-Modulus: ''
  encrypt-Track-Key-Exponent: ''
  jfFrontRequestUrl: ''
  jfBackRequestUrl: ''
  jfSingleQueryUrl: ''
  jfCardRequestUrl: ''
  jfAppRequestUrl: ''
  
  
  #回调地址
  notify_url: http://smi25.xingmeihui.com/smipay/uncallback.do;
  #前台返回地址
  return_url: http://smi25.xingmeihui.com/smipay/unreturn.do;
    
  
---
# Test environment
spring:
  # PROFILES
  profiles: test
  
acpsdk:
  #商户ID
  merId: 777290058127880
  
  ##交易请求地址 
  
  frontRequestUrl: https://101.231.204.80:5000/gateway/api/frontTransReq.do
  backRequestUrl: https://101.231.204.80:5000/gateway/api/backTransReq.do
  singleQueryUrl: https://101.231.204.80:5000/gateway/api/queryTrans.do
  batchTransUrl: https://101.231.204.80:5000/gateway/api/batchTrans.do
  fileTransUrl: https://101.231.204.80:9080/
  appRequestUrl: https://101.231.204.80:5000/gateway/api/appTransReq.do
  cardRequestUrl: https://101.231.204.80:5000/gateway/api/cardTransReq.do
   #linux下（注意：在linux下读取证书需要保证证书有被应用读的权限）
  sign-Cert-Path: /assets/acp_test_sign.pfx
    ##签名证书密码，测试环境固定000000，生产环境请修改为从cfca下载的正式证书的密码，正式环境证书密码位数需小于等于6位，否则上传到商户服务网站会失败
  sign-Cert-Pwd: '000000'
    ##签名证书类型，固定不需要修改
  sign-Cert-Type: PKCS12
  ##########################验签证书配置################################
  ##验证签名证书目录，只配置到目录即可，必须使用绝对路径，如果不想使用绝对路径，可以自行实现相对路径获取证书的方法；测试证书所有商户共用开发包中的测试验证证书，生产环境所有商户共用开发包中的生产验签证书
  #windows下
  #acpsdk.validateCert.dir=D:/certs/
  #linux下（注意：在linux下读取证书需要保证证书有被应用读的权限）
  validate-Cert-Dir: /assets/
   
    
  ##########################加密证书配置################################
  ##敏感信息加密证书路径(商户号开通了商户对敏感信息加密的权限，需要对 卡号accNo，pin和phoneNo，cvn2，expired加密（如果这些上送的话），对敏感信息加密使用)
  encrypt-Cert-Path: E:/assets/acp_test_enc.cer
  
  singleMode: true
  
  
  encrypt-Track-Cert-Path: ''
  encrypt-Track-Key-Modulus: ''
  encrypt-Track-Key-Exponent: ''
  jfFrontRequestUrl: ''
  jfBackRequestUrl: ''
  jfSingleQueryUrl: ''
  jfCardRequestUrl: ''
  jfAppRequestUrl: ''

  #回调地址
  notify_url: http://smi25.xingmeihui.com/smipay/uncallback.do;
  #前台返回地址
  return_url: http://smi25.xingmeihui.com/smipay/unreturn.do;
---
# Production environment
spring:
  # PROFILES
  profiles: production

acpsdk:
  #商户ID
  merId: 777290058110048
  
  ##交易请求地址 
  
  frontRequestUrl: https://gateway.95516.com/gateway/api/frontTransReq.do
  backRequestUrl: https://gateway.95516.com/gateway/api/backTransReq.do
  singleQueryUrl: https://gateway.95516.com/gateway/api/queryTrans.do
  batchTransUrl: https://gateway.95516.com/gateway/api/batchTrans.do
  fileTransUrl: https://filedownload.95516.com/
  appRequestUrl: https://gateway.95516.com/gateway/api/appTransReq.do
  cardRequestUrl: https://gateway.95516.com/gateway/api/cardTransReq.do
  
    #linux下（注意：在linux下读取证书需要保证证书有被应用读的权限）
  sign-Cert-Path: /assets/certify-0850-WEB.pfx
    ##签名证书密码，测试环境固定000000，生产环境请修改为从cfca下载的正式证书的密码，正式环境证书密码位数需小于等于6位，否则上传到商户服务网站会失败
  sign-Cert-Pwd: 150728
    ##签名证书类型，固定不需要修改
  sign-Cert-Type: PKCS12
  ##########################验签证书配置################################
  ##验证签名证书目录，只配置到目录即可，必须使用绝对路径，如果不想使用绝对路径，可以自行实现相对路径获取证书的方法；测试证书所有商户共用开发包中的测试验证证书，生产环境所有商户共用开发包中的生产验签证书
  #windows下
  #acpsdk.validateCert.dir=D:/certs/
  #linux下（注意：在linux下读取证书需要保证证书有被应用读的权限）
  validate-Cert-Dir: /assets/
   
    
  ##########################加密证书配置################################
  ##敏感信息加密证书路径(商户号开通了商户对敏感信息加密的权限，需要对 卡号accNo，pin和phoneNo，cvn2，expired加密（如果这些上送的话），对敏感信息加密使用)
  encrypt-Cert-Path: /assets/acp20151027.cer
  
  singleMode: true
  
  encrypt-Track-Cert-Path: ''
  encrypt-Track-Key-Modulus: ''
  encrypt-Track-Key-Exponent: ''
  jfFrontRequestUrl: ''
  jfBackRequestUrl: ''
  jfSingleQueryUrl: ''
  jfCardRequestUrl: ''
  jfAppRequestUrl: ''
  
  #回调地址
  notify_url: http://smi25.xingmeihui.com/smipay/uncallback.do
  #前台返回地址
  return_url: http://smi25.xingmeihui.com/smipay/unreturn.do