# ----------------------------------------
# CORE PROPERTIES
# ----------------------------------------

# BANNER
banner:
  charset: UTF-8

spring:
  # IDENTITY
  application:
    name: SMI Member API Service
  # AOP
  aop:
    auto: true
    proxy-target-class: false
  # FILE ENCODING (FileEncodingApplicationListener)
  mandatory-file-encoding: utf-8
  # HTTP encoding (HttpEncodingProperties)
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  # JACKSON (JacksonProperties)
  jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
#  # DATASOURCE COMMON PROPERTIES
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    connection-timeout: 2000
#    maximum-pool-size: 20
#    type: com.alibaba.druid.pool.DruidDataSource
  # INTERNATIONALIZATION (MessageSourceAutoConfiguration)
  messages:
    encoding: utf-8
    basename: i18n/common_zh_CN

## MAYBATIS PROPERTIES
#mybatis:
#  check-config-location: true
#  config-location: classpath:mybatis-config.xml
#  mapper-locations: classpath:mybatis-mapper/**/*.xml
#  type-aliases-package: #{type-aliases-package}
#  #type-handlers-package: #{type-handlers-package}

# EMBEDDED SERVER CONFIGURATION (ServerProperties)
server:
  display-name: SMI Member API Service
  connection-timeout: 120000
  compression:
    enabled: true
    mime-types: application/json
  error:
    include-stacktrace: always
    whitelabel:
      enabled: true
  undertow:
    buffer-size: #{buffer-size}
    buffers-per-region: #{buffers-per-region}
    direct-buffers: #{direct-buffers}
    io-threads: 32
    worker-threads: 160

# LOGGING
logging:
  level.root: info

# ----------------------------------------
# ACTUATOR PROPERTIES
# ----------------------------------------

# ENDPOINTS (AbstractEndpoint subclasses)
endpoints:
  shutdown:
    enabled: true
    sensitive: false
management:
  context-path: /system-manager
  security:
    enabled: true
    role: ADMIN

# ----------------------------------------
# SECURITY PROPERTIES
# ----------------------------------------
# SECURITY (SecurityProperties)
security:
  basic:
    enabled: true
    path: /system-manager
  user:
    name: smiadmin
    password: 123qwe
  # SECURITY OAUTH2
  oauth2:
    # RESOURCES (ResourceServerProperties)
    resource:
      id: member-api-service
    # CLIENT (OAuth2ClientProperties)
    client:
      client-id: smiadmin

# ----------------------------------------
# PROFILES PROPERTIES
# ----------------------------------------

---
# Development environment
spring:
  # PROFILES
  profiles: development
#  # DATASOURCE COMMON PROPERTIES
#  datasource:
#    url: jdbc:mysql://192.168.68.23:3306/smi_mapi?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
#    username: root
#    password: fvt6eip
  # REDIS (RedisProperties)
  redis:
    host: 192.168.68.23
    port: 6379

# SECURITY OAUTH2
security:
  # SECURITY OAUTH2
  oauth2:
    # RESOURCES (ResourceServerProperties)
    resource:
      token-info-uri: http://192.168.68.21:9527/oauth/check_token
    # CLIENT (OAuth2ClientProperties)
    client:
      client-secret: 123qwe

# LOGGING
logging:
  level.com.smi: debug

# EMBEDDED SERVER CONFIGURATION (ServerProperties)
server:
  port: 8090
  context-path: /

---
# Test environment
spring:
  # PROFILES
  profiles: test
#  # DATASOURCE COMMON PROPERTIES
#  datasource:
#    url: jdbc:mysql://192.168.68.21:3306/smi_mapi?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
#    username: root
#    password: fvt6eip
  # REDIS (RedisProperties)
  redis:
    host: 192.168.68.23
    port: 6379

# SECURITY OAUTH2
security:
  # SECURITY OAUTH2
  oauth2:
    # RESOURCES (ResourceServerProperties)
    resource:
      token-info-uri: http://192.168.68.21:9527/oauth/check_token
    # CLIENT (OAuth2ClientProperties)
    client:
      client-secret: 123qwe

# LOGGING
logging:
  path: /logs/member-api-service
  level.com.smi: warn

# EMBEDDED SERVER CONFIGURATION (ServerProperties)
server:
  port: 8090
  context-path: /
  undertow:
    accesslog:
      enabled: true
      dir: /logs/member-api-service

---
# Production environment
spring:
  # PROFILES
  profiles: production
#  # DATASOURCE COMMON PROPERTIES
#  datasource:
#    url: #{url}
#    username: #{username}
#    password: #{password}
  # REDIS (RedisProperties)
  redis:
    host: 192.168.86.19
    port: 6379

# SECURITY OAUTH2
security:
  # SECURITY OAUTH2
  oauth2:
    # RESOURCES (ResourceServerProperties)
    resource:
      token-info-uri: http://192.168.94.7:9527/oauth/check_token
    # CLIENT (OAuth2ClientProperties)
    client:
      client-secret: smi@smi-cloud

# LOGGING
logging:
  path: /logs/member-api-service
  level.com.smi: info

# EMBEDDED SERVER CONFIGURATION (ServerProperties)
server:
  port: 8090
  context-path: /
  undertow:
    accesslog:
      enabled: true
      dir: /logs/member-api-service